### ISSUE TITLE
New issue with Docker build

### ISSUE THREAD

**Issue by psmith3** [UniversalDevicesInc/polyglot-v2#108]
Hi guys, I realized this week that my Polyglot V2 had stopped running on my Synology NAS and I am seeing an issue I cannot find. I had a dockerfile and docker-compose file that have worked like a champ for the last year until now. Something has updated and I am not sure what. I have reverted back to the original dockerfile from this repository and started over, but still seeing the issue in my log for polyglot below. It is probably something simple that I am not seeing. Could it be an issue with Node:10-Alpine? Path issue? Any thoughts?

--
> node bin/polyglot-v2
> polyglot-v2@2.2.11 start /opt/polyglot-v2
 
[0m
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /root/.npm/_logs/2022-01-13T21_45_23_397Z-debug.log
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:
[0m
[0m[37;40mnpm[0m [0m[30;43mWARN[0m[35m[0m Local package.json exists, but node_modules missing, did you mean to install?
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m This is probably not a problem with npm. There is likely additional logging output above.
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Failed at the polyglot-v2@2.2.11 start script.
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Exit status 1
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m polyglot-v2@2.2.11 start: `node bin/polyglot-v2`
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35merrno[0m 1
[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m ELIFECYCLE
at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
at startup (internal/bootstrap/node.js:283:19)
at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
Error: Cannot find module '/opt/polyglot-v2/bin/polyglot-v2'
 
^
throw err;
internal/modules/cjs/loader.js:638

**Comment by psmith3** [comment]
@Einstein42, Is anyone else having issue running in Docker now or elsewhere that you know of? I loaded node:10-alpine in a docker container on its own and manually installed the prerequisites in the docker-compose file and and still seeing the same issue below. I've tried node:12-alpine and see the same behavior. 

npm ERR! Exit status 1                                                                                                                                                                                                  
npm ERR!                                                                                                                                                                                                                
npm ERR! Failed at the polyglot-v2@2.2.11 start script.                                                                                                                                                                 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                      
                                                                                                                                                                                                                        
npm ERR! A complete log of this run can be found in:                                                                                                                                                                    
npm ERR!     /root/.npm/_logs/2022-01-16T23_37_24_938Z-debug.log                                                                                                                                                        
/opt/polyglot-v2/bin # cd bin                                                                                                                                                                                           
/bin/ash: cd: can't cd to bin: No such file or directory                                                                                                                                                                
/opt/polyglot-v2/bin # npm start                                                                                                                                                                                        
                                                                                                                                                                                                                        
> polyglot-v2@2.2.11 start /opt/polyglot-v2                                                                                                                                                                             
> node bin/polyglot-v2                                                                                                                                                                                                  
                                                                                                                                                                                                                        
npm ERR! code ELIFECYCLE                                                                                                                                                                                                
npm ERR! errno 1                                                                                                                                                                                                        
npm ERR! polyglot-v2@2.2.11 start: `node bin/polyglot-v2`                                                                                                                                                               
npm ERR! Exit status 1                                                                                                                                                                                                  
npm ERR!                                                                                                                                                                                                                
npm ERR! Failed at the polyglot-v2@2.2.11 start script.                                                                                                                                                                 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                      
                                                                                                                                                                                                                        
npm ERR! A complete log of this run can be found in:                                                                                                                                                                    
npm ERR!     /root/.npm/_logs/2022-01-16T23_37_44_085Z-debug.log
                                                                                                                                                        
cat 2022-01-16T23_37_44_085Z-debug.log                                                                                                                                                                   
0 info it worked if it ends with ok                                                                                                                                                                                     
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]                                                                                                                                                  
2 info using npm@6.14.12                                                                                                                                                                                                
3 info using node@v10.24.1                                                                                                                                                                                              
4 verbose run-script [ 'prestart', 'start', 'poststart' ]                                                                                                                                                               
5 info lifecycle polyglot-v2@2.2.11~prestart: polyglot-v2@2.2.11                                                                                                                                                        
6 info lifecycle polyglot-v2@2.2.11~start: polyglot-v2@2.2.11                                                                                                                                                           
7 verbose lifecycle polyglot-v2@2.2.11~start: unsafe-perm in lifecycle true                                                                                                                                             
8 verbose lifecycle polyglot-v2@2.2.11~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/polyglot-v2/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/
bin                                                                                                                                                                                                                     
9 verbose lifecycle polyglot-v2@2.2.11~start: CWD: /opt/polyglot-v2                                                                                                                                                     
10 silly lifecycle polyglot-v2@2.2.11~start: Args: [ '-c', 'node bin/polyglot-v2' ]                                                                                                                                     
11 silly lifecycle polyglot-v2@2.2.11~start: Returned: code: 1  signal: null                                                                                                                                            
12 info lifecycle polyglot-v2@2.2.11~start: Failed to exec start script                                                                                                                                                 
13 verbose stack Error: polyglot-v2@2.2.11 start: `node bin/polyglot-v2`                                                                                                                                                
13 verbose stack Exit status 1                                                                                                                                                                                          
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)                                                                                           
13 verbose stack     at EventEmitter.emit (events.js:198:13)                                                                                                                                                            
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)                                                                                        
13 verbose stack     at ChildProcess.emit (events.js:198:13)                                                                                                                                                            
13 verbose stack     at maybeClose (internal/child_process.js:982:16)                                                                                                                                                   
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)                                                                                                                           
14 verbose pkgid polyglot-v2@2.2.11                                                                                                                                                                                     
15 verbose cwd /opt/polyglot-v2/bin                                                                                                                                                                                     
16 verbose Linux 3.10.108                                                                                                                                                                                               
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"                                                                                                                                                      
18 verbose node v10.24.1                                                                                                                                                                                                
19 verbose npm  v6.14.12                                                                                                                                                                                                
20 error code ELIFECYCLE                                                                                                                                                                                                
21 error errno 1                                                                                                                                                                                                        
22 error polyglot-v2@2.2.11 start: `node bin/polyglot-v2`                                                                                                                                                               
22 error Exit status 1                                                                                                                                                                                                  
23 error Failed at the polyglot-v2@2.2.11 start script.                                                                                                                                                                 
23 error This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                      
24 verbose exit [ 1, true ]                                                                                                                                                                                             
~/.npm/_logs
