### ISSUE TITLE
MongoError: connection 265 to localhost:27017 timed out

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc/polyglot-v2#37]
Something caused the RPi to get totally thrashed, so the user could not even log in, so this is just a symptom of that.  But, the message says report this, so I'm reporting it.
```
2018-7-12 08:57:06 - info: MQTTS: Client Connected: HarmonyHub
2018-7-12 08:57:06 - info: HarmonyHub(3): Processing command: connected
2018-7-12 08:57:07 - info: HarmonyHub(3): NodeServer Connected.
2018-7-12 08:57:07 - info: HarmonyHub(3): n003_harmonyctrl ST set sucessfully to 1 : UOM 2
2018-7-12 08:58:16 - error: MQTTS: keepaliveTimeout: HarmonyHub
2018-7-12 09:02:34 - error: MQTTS: clientError: HarmonyHub keep alive timeout
2018-7-12 09:34:37 - info: MQTTS: Client Disconnected: HarmonyHub
2018-7-12 09:34:50 - info: MQTTS: Client Connected: HarmonyHub
2018-7-12 09:34:52 - info: MQTTS: Client Disconnected: HarmonyHub
2018-7-12 09:34:57 - info: MQTTS: Client Connected: HarmonyHub
2018-7-12 09:34:59 - info: HarmonyHub(3): Processing command: connected
2018-7-12 09:35:07 - info: HarmonyHub(3): NodeServer Connected.
2018-7-12 09:35:29 - info: HarmonyHub(3): n003_harmonyctrl ST set sucessfully to 1 : UOM 2
2018-7-12 09:35:45 - error: MQTTS: clientError: HarmonyHub write EPIPE
2018-7-12 10:05:11 - info: MQTTS: Client Disconnected: HarmonyHub
2018-7-12 10:05:20 - error: unhandledRejection REPORT THIS!: MongoError: connection 265 to localhost:27017 timed out
    at Function.MongoError.create (/snapshot/polyglot-v2/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.timeoutHandler (/snapshot/polyglot-v2/node_modules/mongodb-core/lib/connection/connection.js:200:20)
    at Object.onceWrapper (events.js:254:19)
    at Socket.emit (events.js:159:13)
    at Socket._onTimeout (net.js:411:8)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
2018-7-12 10:05:21 - info: MQTTS: Client Connected: HarmonyHub
```

**Comment by exking** [comment]
Get a faster Pi? :)
