### ISSUE TITLE
Port issues?

### ISSUE THREAD

**Issue by sdasmith** [UniversalDevicesInc/polyglot-v2#40]
Any help with this error?
`pi@raspberrypi:~ $ tail -f ~/.polyglot/log/debug.log
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1496:7)
    at /snapshot/polyglot-v2/lib/services/mqtts.js:134:27
    at new Promise (<anonymous>)
    at Object.start (/snapshot/polyglot-v2/lib/services/mqtts.js:131:15)
    at start (/snapshot/polyglot-v2/bin/polyglot-v2.js:76:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-9-6 00:47:36 - info: Starting Polyglot....
2018-9-6 00:47:37 - info: Settings: Polyglot Version 2.2.1
2018-9-6 00:47:37 - info: Settings: Features {"noticeByKey":"on","customParamsDoc":"on","typedParams":"on"}
2018-9-6 00:47:37 - info: Settings: Retrieved config from database
2018-9-6 00:47:37 - info: Settings: Retrieved config overrides from .env and updated database
2018-9-6 00:47:37 - error: uncaughtException: listen EADDRINUSE :::1883 date=Thu Sep 06 2018 00:47:37 GMT+0000 (UTC), pid=549, uid=1000, gid=1000, cwd=/home/pi/polyglot, execPath=/home/pi/polyglot/polyglot-v2-linux-armv6, version=v9.2.1, argv=[/home/pi/polyglot/polyglot-v2-linux-armv6, /snapshot/polyglot-v2/bin/polyglot-v2.js], rss=70193152, heapTotal=41418752, heapUsed=28457012, external=19670223, loadavg=[1.49951171875, 0.60888671875, 0.22998046875], uptime=116
Error: listen EADDRINUSE :::1883
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1496:7)
    at /snapshot/polyglot-v2/lib/services/mqtts.js:134:27
    at new Promise (<anonymous>)
    at Object.start (/snapshot/polyglot-v2/lib/services/mqtts.js:131:15)
    at start (/snapshot/polyglot-v2/bin/polyglot-v2.js:76:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

I did the Install script listed here on a Raspberry Pi Zero:
https://github.com/UniversalDevicesInc/polyglot-v2#installation-instructions

**Comment by i814u2** [comment]
Do you know of anything else using port 1883 on your pi?
That's basically saying that it couldn't start the MQTT portion because the port is in use.
