### ISSUE TITLE
Restart looping due to uncaught exception

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc/polyglot-v2#44]
```
2018-10-21 16:45:28 - info: Starting Polyglot....
2018-10-21 16:45:29 - info: Settings: Polyglot Version 2.2.1
2018-10-21 16:45:29 - info: Settings: Features {"noticeByKey":"on","customParamsDoc":"on","typedParams":"on"}
2018-10-21 16:45:29 - info: Settings: Retrieved config from database
2018-10-21 16:45:29 - info: Settings: Retrieved config overrides from .env and updated database
2018-10-21 16:45:29 - info: Aedes MQTT Broker Service: Started on port 1883
2018-10-21 16:45:30 - info: MQTT Client Service: Started
2018-10-21 16:45:30 - info: HTTPS Interface Service: Started - Address: 0.0.0.0 Port: 3000
2018-10-21 16:45:31 - info: Hue(3): Completed ReSync with ISY.
2018-10-21 16:45:31 - info: NS: Starting Local NodeServer Hue profile number 3 :: Version 0.1.7
2018-10-21 16:45:31 - info: MQTTS: polyglot authenticated successfully.
2018-10-21 16:45:31 - info: MQTTS: Client Connected: polyglot
2018-10-21 16:45:31 - info: ISY: Got Version 5.0.13
2018-10-21 16:45:31 - error: NS checkExistingNodeServers Error: TypeError: Cannot read property 'profile' of undefined
2018-10-21 16:45:32 - error: NSChild STDERR: Hue: Traceback (most recent call last):
  File "./hue.py", line 9, in <module>
    import polyinterface as polyglot
ImportError: No module named 'polyinterface'

2018-10-21 16:45:32 - error: uncaughtException: read ECONNRESET date=Sun Oct 21 2018 16:45:32 GMT-0500 (CDT), pid=17490, uid=1000, gid=1000, cwd=/home/pi/polyglot, execPath=/home/pi/polyglot/polyglot-v2-linux-armv7, version=v9.2.1, argv=[/home/pi/polyglot/polyglot-v2-linux-armv7, /snapshot/polyglot-v2/bin/polyglot-v2.js], rss=77799424, heapTotal=51986432, heapUsed=36685496, external=19168847, loadavg=[1.10400390625, 0.99755859375, 0.8671875], uptime=1251
Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at Pipe.onread (net.js:619:25)
2018-10-21 16:45:40 - info: Starting Polyglot....
```

**Comment by jimboca** [comment]
@brianmtreese looks like your nodeserver is using python 2, try switching to python 3.  That __features__ stuff was added by @firstone a while back not sure why it's not working for your install.

**Comment by brianmtreese** [comment]
@jimboca thanks! I'll give it a try.

**Comment by brianmtreese** [comment]
That was totally the problem, thanks @jimboca!

**Comment by jimboca** [comment]
Nice! Someone needs to look at the python 2 and see why it's broken?
