### ISSUE TITLE
Polyglot - Not connected to server

### ISSUE THREAD

**Issue by pgattu** [UniversalDevicesInc/polyglot-v2#65]
I am getting the following error.  I tried refreshing the page, but error remains.  Please help.

`Not connected to server... Try refreshing the page. This will disappear once the connection is re-established.`

**Comment by pgattu** [comment]
The above issue started as soon as I installed the Tesla node server.  I am unable to delete the Tesla node server, since it says that I am not connected.

**Comment by pgattu** [comment]
In the Polyglot Log, I see the following error:

```
2019-5-25 20:13:40 - error: NSChild STDERR: Tesla: /home/pi/.polyglot/nodeservers/Tesla/nodeserver.js:264
    logger.error(`uncaughtException REPORT THIS!: ${err.stack}`);
    ^
ReferenceError: logger is not defined
    at process.<anonymous> (/home/pi/.polyglot/nodeservers/Tesla/nodeserver.js:264:5)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:375:26)
```

**Comment by pgattu** [comment]
I was able to delete Tesla node server and the Polyglot server stabilized.  Closing issue.
